version: '3.8'
services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app          # монтируем весь проект внутрь контейнера
      - /usr/src/app/node_modules  # чтобы node_modules не затиралось локальными файлами
    command: npm run start:dev  # запускаем с watch режимом
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data